### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by david-brauer** [emilioastarita/lyricfier#21] opened 2016-12-05 16:39 UTC
It would be nice to have a button to change the font-size. In developer options this already works with e.g. fon-size:25pt, but after closing the programm restores the default font-size.

**Comment by mrkmndz** [comment] 2016-12-10 23:37
Hey @emilioastarita is this something that we would want in the currently inaccessible Settings view? Perhaps also including an adjuster for refresh time?

**Comment by emilioastarita** [comment] 2016-12-10 23:51
@mrkmndz yes. That settings page was intended for this kind of adjustment. Also we can add the dark theme switcher there. Do you want to work in this issue?

**Comment by mrkmndz** [comment] 2016-12-10 23:54
Sure, I should be able to put that along with always on top

**Comment by mrkmndz** [comment] 2016-12-11 22:08
closed by #34

**Comment by mrkmndz** [comment] 2016-12-12 00:23
@emilioastarita can you close this?

**Closed as completed** 2016-12-12 00:23 UTC
